USE [master]
GO

/****** Object:  Database [MedorExample]    Script Date: 4/10/2025 1:27:52 AM ******/
CREATE DATABASE [MedorExample]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MedorExample', FILENAME = N'C:\Users\codea\MedorExample.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MedorExample_log', FILENAME = N'C:\Users\codea\MedorExample_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MedorExample].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MedorExample] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MedorExample] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MedorExample] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MedorExample] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MedorExample] SET ARITHABORT OFF 
GO

ALTER DATABASE [MedorExample] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MedorExample] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MedorExample] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MedorExample] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MedorExample] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MedorExample] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MedorExample] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MedorExample] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MedorExample] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MedorExample] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MedorExample] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MedorExample] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MedorExample] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MedorExample] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MedorExample] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MedorExample] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MedorExample] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MedorExample] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MedorExample] SET  MULTI_USER 
GO

ALTER DATABASE [MedorExample] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MedorExample] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MedorExample] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MedorExample] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MedorExample] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MedorExample] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MedorExample] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MedorExample] SET  READ_WRITE 
GO

USE [MedorExample]
GO

/****** Object:  Table [dbo].[Rates]    Script Date: 4/10/2025 1:34:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [MedorExample].[dbo].[Rates](
	[ID] [int] NOT NULL,
	[CODE] [nchar](10) NOT NULL,
	[VALUE] [nchar](20) NOT NULL,
	[VALID] [datetime] NOT NULL,
	[NOTE] [nchar](400) NULL,
	CONSTRAINT PK_Rates_RateID PRIMARY KEY CLUSTERED (ID)
) ON [PRIMARY]
GO


